function [testData,t] = importfile4(filename, dataLines)
%IMPORTFILE Import data from a text file
%  testData = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  testData = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  testData = importfile("C:\_PhD\4_Tez\3_Tests\1_TestData\20260107\txtData\Hasan_PhD_RMC200_all_0_20260107_193857313.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Jan-2026 00:05:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);
t = struct; 
% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
% opts.VariableNames = ["Timesec", "xc_mmTargetPositionmm", "xc_mmActualPositionmm", "xc_mmControlOutput", "Q_return_lpmActualPositionlpm", "P_A_barActualPressurebar", "P_B_barActualPressurebar", "P_supply_barActualPressurebar", "P_return_barActualPressurebar", "T_supply_degActualPositionC", "xc_mmPositionErrormm", "xc_mmTargetVelocitymms", "xc_mmActualVelocitymms", "xc_mmActualAccelmms", "P_L_bar", "F_piston_N", "xc_mmFinalOutputV", "AccActualPositiong", "F_piston_N_fromA", "xc_mmTargetAccelmms", "Acc_mms2"];
% opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];


% Specify column names and types
opts.VariableNames = ["t", "r_mm", "xc_mm", "u_perc", "Q_return_lpm", "PA_bar", "PB_bar", "P_supply_bar", "P_return_bar", "T_supply_deg", "e_mm", "r_v_mmPs", "v_mmPs", "a_RMC_mmPs2", "PL_bar", "F_piston_N", "u_V", "a_G", "F_piston_from_a_N", "r_a_RMC_mmPs2", "a_mmPs2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];



% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testData = readtable(filename, opts);

t.t 	            =	 testData.t; 	                    %	Time	s
t.r_m 	            =	 testData.r_mm * 1e-3; 	            %	Cylinder Position Reference	m
t.xc_m 	            =	 testData.xc_mm * 1e-3; 	        %	Cylinder Position Actual 	
t.u_perc 	        =	 testData.u_perc; 	                %	Control Output	%
t.Q_return_m3Ps 	=	 testData.Q_return_lpm * (1/60e3);	%	Return Flow	m3Ps
t.PA_Pa 	        =	 testData.PA_bar * 1e5; 	        %	Pressure A (Cap Side)	Pa
t.PB_Pa 	        =	 testData.PB_bar * 1e5; 	        %	Pressure B (Rod End Side)	Pa
t.P_supply_Pa 	    =	 testData.P_supply_bar * 1e5;	    %	Pressure Supply	Pa
t.P_return_Pa 	    =	 testData.P_return_bar * 1e5;	    %	Pressure Return 	Pa
t.T_supply_deg 	    =	 testData.T_supply_deg;	            %	Temperature Oil	deg
t.e_m 	            =	 testData.e_mm * 1e-3;	            %	Cylinder Position Error	m
t.r_v_mPs 	        =	 testData.r_v_mmPs * 1e-3;	        %	Cylinder Velocity Reference	mPs
t.v_mPs 	        =	 testData.v_mmPs * 1e-3;	        %	Cylinder Velocity Actual	mPs
t.a_RMC_mPs2    	=	 testData.a_RMC_mmPs2 * 1e-3;	    %	Cylinder Acceleration Actual (calculated with derivative)	mPs2
t.PL_Pa 	        =	 testData.PL_bar * 1e5;	            %	Pressure Difference	Pa
t.F_piston_N 	    =	 testData.F_piston_N;	            %	Force Piston (calculated from pressure difference * Aeff)	N
t.u_V 	            =	 testData.u_V;	                    %	Control Output 	V
t.a_mPs2 	        =	 testData.a_G * 9.80665;	        %	Cylinder Acceleration Actual (measured)	mPs2
t.F_piston_from_a_N =	 testData.F_piston_from_a_N;	    %	Force Piston (calculated from m*a)	N
t.r_a_RMC_mPs2 	    =	 testData.r_a_RMC_mmPs2 * 1e-3;	    %	Acceleration Reference 	mPs2

    


end