function [t,r,xc,u_perc,Q_return,P_A, P_B, P_supply, P_return,T_supply,e,r_dot, xc_dot,P_L, F_piston, Ts,Fs] = importfile2(data, dataLines)
%IMPORTFILE Import data from a text file
%  TESTDATA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TESTDATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  testData = importfile("D:\Personal_Folders\HasanSener\_PhD\1_TestData\sine_plus_step_0.45offset_5p_100i.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Sep-2025 10:39:09
%% CONSTANTS 
mm2m        = 1e-3; 
bar2Pa      = 100e3; 
mmPs2mPs    = 1e-3; 
lpm2m3Ps    = 1/60e3; 

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Timesec", "xc_mmTargetPositionmm", "xc_mmActualPositionmm", "xc_mmControlOutput", "Q_return_lpmActualPositionlpm", "P_A_barActualPressurebar", "P_B_barActualPressurebar", "P_supply_barActualPressurebar", "P_return_barActualPressurebar", "T_supply_degActualPositionC", "xc_mmPositionErrormm", "xc_mmActualVelocitymms", "xc_mmTargetVelocitymms", "P_L_bar", "F_piston_N"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testData = readtable(data, opts);
% Seperate test data 
t           = testData.Timesec;                             % Time (s)
r           = testData.xc_mmTargetPositionmm;               % Reference target cylinder position (mm)
xc          = testData.xc_mmActualPositionmm;                  % Actual cylinder position (mm)
u           = testData.xc_mmControlOutput;                  % Command sent to servo-valve (%+/-100) --> Converted to +/-50mA by using VC2421 V->i converter
Q_return    = testData.Q_return_lpmActualPositionlpm;       % Supply flow measured from pressure line input to servo valve (lpm)
P_A         = testData.P_A_barActualPressurebar;            % Extension chamber pressure (bar) 
P_B         = testData.P_B_barActualPressurebar;            % Compression chamber pressure (bar) 

P_supply    = testData.P_supply_barActualPressurebar;       % Supply pressure (bar)
P_return    = testData.P_return_barActualPressurebar;       % Return pressure (bar)
T_supply    = testData.T_supply_degActualPositionC;         % Supply temperature (°C)

e           = testData.xc_mmPositionErrormm;                % Position error in the closed loop control (mm)
r_xc_dot    = testData.xc_mmTargetVelocitymms;              % Target velocity (mm/s) 
xc_dot      = testData.xc_mmActualVelocitymms;              % Cylinder velocity (mm/s)


P_L         = testData.P_L_bar;                             % Load pressure (bar)
F_piston    = testData.F_piston_N;                          % Generated Piston Force (N)


r   = r * mm2m; 
xc  = xc * mm2m; 
u_perc = u;
Q_return = Q_return * lpm2m3Ps; 
P_A = P_A * bar2Pa; 
P_B = P_B * bar2Pa; 
P_L = P_L * bar2Pa; 

P_supply = P_supply * bar2Pa; 
P_return = P_return * bar2Pa; 

e  = e * mm2m;

xc_dot = xc_dot * mmPs2mPs;
r_dot = r_xc_dot * mmPs2mPs;

Ts = mean(diff(t));
Fs = 1/Ts;

end