function [t,r,y,u,Q_supply,P_A, P_B, P_supply, P_return,T_supply,e,y_dot,Ts,Fs] = importfile(data, dataLines)
%IMPORTFILE Import data from a text file
%  TESTDATA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TESTDATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  testData = importfile("D:\Personal_Folders\HasanSener\_PhD\1_TestData\sine_plus_step_0.45offset_5p_100i.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Sep-2025 10:39:09

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Timesec", "ramPos_mmTargetPositionmm", "ramPos_mmActualPositionmm", "ramPos_mmControlOutput", "dec_supplyFlow_lpmActualPositionlpm", "dec_chamberA_barActualPressurebar", "dec_chamberB_barActualPressurebar", "dec_supplyPressure_barActualPressurebar", "dec_returnPresure_barActualPressurebar", "dec_supplyTemperature_degActualPositionC", "ramPos_mmPositionErrormm", "ramPos_mmActualVelocitymms"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testData = readtable(data, opts);
% Seperate test data 
t           = testData.Timesec; % Time (s)
r           = testData.ramPos_mmTargetPositionmm; % Reference target cylinder position (mm)
y           = testData.ramPos_mmActualPositionmm; % Actual cylinder position (mm)
u           = testData.ramPos_mmControlOutput;  % Command sent to servo-valve (%+/-100) --> Converted to +/-50mA by using VC2421 V->i converter
Q_supply    = testData.dec_supplyFlow_lpmActualPositionlpm; % Supply flow measured from pressure line input to servo valve (lpm)
P_A         = testData.dec_chamberA_barActualPressurebar; % Extension chamber pressure (bar) 
P_B         = testData.dec_chamberB_barActualPressurebar; % Compression chamber pressure (bar) 

P_supply    = testData.dec_supplyPressure_barActualPressurebar; % Supply pressure (bar)
P_return    = testData.dec_returnPresure_barActualPressurebar;  % Return pressure (bar)
T_supply    = testData.dec_supplyTemperature_degActualPositionC; % Supply temperature (°C)

e           = testData.ramPos_mmPositionErrormm; % Position error in the closed loop control (mm)
y_dot       = testData.ramPos_mmActualVelocitymms; % Cylinder velocity (mm/s)

Ts = mean(diff(t));
Fs = 1/Ts;

end